# Avatar Framer Config
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

######################################################
# NEEDED FOR GITHUB PAGES TO WORK WITH RELATIVE URLS #
######################################################
baseurl: ""
######################################################

title: Tạo avatar của bạn
description: >- # this means to ignore newlines"
  Ứng dụng tạo ảnh avatar

# Copy
# Fill in your copy for the title and steps here
# 
title-text: "Ứng dụng tạo ảnh đại diện với khung hình nhanh chóng"
step-1: "Tải hình của bạn lên"
step-2: "Sử dụng công cụ bên cạnh để chỉnh sửa hình ảnh theo ý muốn"
step-3: "Chọn khung hình mà bạn muốn"
step-4: "Tải hình đại diện của bạn xuống"
step-5: "Đăng tải lên trang cá nhân của bạn"
footer-text: "&copy; 2023 Faculty of Information Technology, Lac Hong University. All rights reserved."

# Header Nav Link
#
nav-link: "https://lhu.edu.vn"
nav-link-text: "Trang chủ"

# Buttons and upload form
# 
upload-text: "Kéo thả tệp tin hoặc nhấp chọn tại đây."
download-button-text: "Tải hình đại diện"

# Logo & Favicon
# 
logo: "logo.png"
favicon: "favicon.ico"

# Footer links
# 
footer-links:
  - text: "Khoa Công nghệ Thông Tin"
    link: "https://cs.lhu.edu.vn"

  - text: "Fanpage CLB Công nghệ Ứng dụng B304"
    link: "https://www.facebook.com/lhub304"

# Open Graph and Twitter Cards
#
og-title: Tạo ảnh avatar của bạn
og-description: Tạo ảnh đại diện của bạn với khung hình một cách nhanh chóng
og-url: https://avatar.airobotic.edu.vn
og-image: "og-image.png"
og-image-width: 1280
og-image-height: 640
twitter-card: summary_large_image
twitter-description: Tạo ảnh đại diện của bạn với khung hình một cách nhanh chóng
twitter-image: "og-image.png"
twitter-handle: "@hmcdat"

keep_files:
  - dist/js/bundle.js

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
# 
exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - "*.config.js"
  - "*.config.json"
  - "package*.json"
  - README.md
